---
all:
 children:
  ios_xe_routers:
   children:
    cisco_rtr_lab:
     hosts:
      10.0.0.1
     vars:
      host_creds:
        user: admin
        password: admin@123
      ansible_user: "{{host_creds.user}}"
      ansible_password: "{{host_creds.password}}"
      ansible_connection: network_cli
      ansible_network_os: ios
      command_delay_seconds: 2
    cisco_xr_rtr_lab:
     hosts:
      10.0.0.2
     vars:
      host_creds:
        user: admin 
        password: admin@123
      ansible_user: "{{host_creds.user}}"
      ansible_password: "{{host_creds.password}}"
      ansible_connection: network_cli
      ansible_network_os: iosxr
      command_delay_seconds: 2

